# Generated by Django 4.2.1 on 2023-05-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_pay_options_pay_cat_pay_content_pay_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='cat',
        ),
        migrations.AddField(
            model_name='web',
            name='price',
            field=models.CharField(default=True, max_length=20, verbose_name='Ціна'),
        ),
    ]
