# Generated by Django 4.2.1 on 2023-06-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_pay_cat_web_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web',
            name='price',
            field=models.CharField(default=' грн', max_length=20, verbose_name='Ціна'),
        ),
    ]
