# Generated by Django 4.2.1 on 2023-06-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_web_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='web',
            options={'ordering': ['-time_update', 'title'], 'verbose_name': 'Мій сайт з автозапчастинами', 'verbose_name_plural': 'Мій сайт з автозапчастинами'},
        ),
        migrations.AlterField(
            model_name='web',
            name='price',
            field=models.CharField(max_length=20, verbose_name='Ціна'),
        ),
    ]
